code_car:
    resource: "@CodeCarBundle/Controller/"
    type:     annotation
    prefix:   /cars

danilo_produto:
    resource: "@DaniloProdutoBundle/Controller/"
    type:     annotation

app:
    resource: @AppBundle/Controller/
    type:     annotation
